window.addEventListener('load', function(){
    const textAnim = document.querySelector('h1');

    new Typewriter(textAnim, {
        deleteSpeed: 20
    })
        .changeDelay(20)
        .typeString('Qui suis je ?')
        .pauseFor(300)
        .typeString('<strong> josias, ce roi qui fut l\'auteur de l\'ancien Testament ... <\strong> !')
        .pauseFor(1000)
        .deleteChars(60)
        .typeString('<span style="color: #27ae60;"> Où...<\span> !')
        .pauseFor(1000)
        .deleteChars(7)
        .typeString('<span style="color: #midnightblue;"> josias, ce renoi casanier qui passe ses journées devant son pc<\span> !')
        .pauseFor(1000)
        .deleteChars(64)
        .typeString('<span style="color: #ea39ff;"> A chacun son point de vue<\span> !')
        .pauseFor(1000)
        .deleteChars(27)
        .typeString('<span style="color: #fff6910;"> Oceane ...<\span> !')
        .pauseFor(1000)
        .deleteChars(12)
        .typeString('<span style="color: #fff6910;"> Ton cadeau, est sous tes yeux...<\span> !')
        .pauseFor(1000)
        .deleteChars(34)
        .typeString('<span style="color: #fff6910;"> Tu le veux? si oui...<\span> !')
        .pauseFor(1000)
        .deleteChars(23)
        .typeString('<span style="color: #fff;"> Let\'s go...<\span> !')
        .pauseFor(1000)
        .deleteChars(13)
        .typeString('<span style="color: #fff6910;"> si non...<\span> !')
        .pauseFor(1000)
        .deleteChars(11)
        .typeString('<span style="color: #fff6910;"> j\'espere tu te fais morder par un bébé phoque<\span> !')
        .pauseFor(1000)
        .deleteChars(47)
        .typeString('<span style="color: #fff6910;"> NaaN je rigole mais vas y Clique<\span> !')
        .pauseFor(1000)
        .deleteChars(34)
        .typeString('<span style="color: #fff6910;"> j\'ATTENDS...<\span> !')
        .pauseFor(2000)
        .deleteChars(14)
        .typeString('<span style="color: red;"> Are you reading ?<\span> ')
        .start()


});